apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D6MHJccNmhN7peMoHQFwakbuH6HA+QFkpVY7SgRHqKamsJ0o44k270oXMKjaZxt+e80gtOo3opqUEkraiPXKdFuaE9oFczrPA1153mFkx+6G5Pd1/giq+pUGNlSeU0cQaRatua2dScwmdVAoc0/tRFTmuhQTp4Yt1K3GgREHZUcmdrOeafBc7fI4L0r4VCybAmRZKRcHmXQ8f5FM1hcpTW2KbxgMUG23qmBoXFQ9PW9uF3AeLHGvGOJEgt7XIUpI9thRrCkEp3m5N/imYHyJUZwQkMHDxJD9psNCzkIVX5zaDNzuIAVYSWwg6pG5Gx8Ur4yJUUwUPALfJBRTf0wjQF3RCnRL4fIvP10U3zHdlhUmYysiwJHaU4RmM7ohS4gv,iv:6XC2EDg0SwOh/XRMD9cCsSsS4yqXE64yHt1zkFgpfQ8=,tag:+B1J7wjfDsWLGlU3pPKbBg==,type:str]
    identity.pub: ENC[AES256_GCM,data:YgF0Tm2tt+QB7DC3JUxgdOMTS2Kj4cnQFFwh1VLcMgj73THBDM4osAbujnqcqsLj4WZj0xHHVUwbyjn1Rv6gBMkZNsm3mN89CQlduVj0iM5ESi5ImBmi3EbLm5jrZLW+U86LC2Jl4PoczWcig73RPOVs8nup6Gm0da7RlgTulCbmkLUuM38YeRynLEdoeKXveltFfTwskKT+NU/3Y6IGqolZCzl25NYV7XFqYdcQ5H/xHgtTgKL3z7s5CIMuKft//LoFTPnl/0jC8H2B3g==,iv:LoPo7Sz6wXYcu9eNvciI1zczmVKJdVjKjQ7qfVf3rTs=,tag:kQGAWnWdrfxs6fSqsmFcpw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RembXnS0XtUxF/4+rhDAoUzsyUx9dWq/zXhTNRuOjDpNvCDYNX4I+Uq9soCUA4miRnM1z4FuP4Z7zwpvxky9kDM5gmi/8DkwSXc5SMiPyUdiE3/uqNz1rFAx8T2WDEhuVqCuNE/Ce1sMdniRSDnIy5IJp4Y0Gpe8QXR2Wh88X59OvpgRkEZPkbH71kV/5FZdlfdIdOTwBp5zAJt4r1mdtv5PjdkpDiClJIkd,iv:qoVUagp7PliBg34MwBSct7q6YfISdrJlqS9SErBIkBo=,tag:4eYTPvdd9tT+S6RPeFsqdw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMnFYSHMwNFgzMXVPZTdE
            bDJxcHJKTytRSjRrU0pXR3F1dHVIWVBpcWl3CldsZlk4U3czbHoxOVJEN0dBYkIw
            bS9ocmNwajZKQmk0ZEZsOTJEWW1jR0UKLS0tIFI1dXc2R0NFak8xdEdCd3RMZmZO
            Wm0wc012VUZWVUV6czRVd3ZmVm1GQUEKLjbxMEHgYPhMgCCACkEPYIqIR4+/ouWd
            V/Wv0MKF7rDFmMrNW7PssJam0aI6tMEcZMEtH1QI0PNdDY3msiDjrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T19:45:01Z"
    mac: ENC[AES256_GCM,data:tJP0ypNoY5/EUfTCMk5/goLQ+RCdodnko44iIVEMeayGBp3MMKYJH0ZJdCcQKIGSMGGE/cEjPN9HOMqKybaUzTJNBtpJM0VV1JOyiWRAadRMYKQD5B63uwBNghU0CbxKuUBN7/+0henzN/iNVxTEKT+BF1DcEodeLu551yYHA/I=,iv:e5kWb2H7rJ2n03+fbbdHoV4r5UNTp7KV6s+6HhTFGJs=,tag:120KO7BmtibvuvHVk24CNg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
