apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NvVgNcZnBtPR3kb2fGqNsMRVByWzNXO65E0s5BBwFNbI+RzNSEcp7cNVMX3rbYeQUCOhwbcxtnXtHFeZI2ck32KvBxKf+qrK5Plm1vj2fnDilEJSwsC4aUzp9V7GLibFDfBfS38c8CKYuJABqBHPVvNnqpyR+43aonwMxpdA1ejSji7hrGd8IFA9as8gnRJYi30P92M5u7XyCLV+qfwHMcH1eXRNaEn4gFp3gkJH1O5BKmQArEZGMerRZLMdUZCRMPqeosJXhpv3L049frYijtIzY+QubjvoZ/1+bO9YJr1ixkTJkx2qts4SG05ADUt7cABLY8j2kSmeF5csYsVjERHynGsbaG0wYrZmXsBlAiptIMZgTqfXkvTNMDst3QqE,iv:KnDkisNzFwawRVv/KvzsKQpIQvryYi8EzpHO/M87Dbg=,tag:Ectd1cksHPIcRWNjWpYj6Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:wlIePO63hFwKFMK3qSs37LII3+vtrsZN8DIAVoU6LDLHMsFX9+lm1b/Y6JN2LKAy8CqLFV4yBx5iGamxEunlnjZoji3eAemmLVDwOj3oj3FafD3ZblUefKzkbFF2d4L2GOz10nNMiN5g6Snw2w5dY7ruKZKdGj+pCIyhMdqE4A7iveajMtafftHepIf49JQBPu34f94/8OfVV/Eq1LGJE2tkPys0x4jFeQ391esWF7+0xxC7E4jSBAJ6fmHA5XVtL3AKkUojtjqPxv5YZw==,iv:ydTs75LYIHTqy3PDWWath/PVzsLeDg0Ms4M3ldRydJk=,tag:I9qxa2i07C3u8UUu6vmNag==,type:str]
    known_hosts: ENC[AES256_GCM,data:SUJCwDtPhugE+l1gVVrLN/GD8hn1TZRc3W5qYbXw0CTPAF7mevQPKZ8aG+nx36B1FYhAuGNmrcD0Fo5qfrGiLRUWMC65usFXCoJx+RHSv0Oaa8p+8KKC6HrWfqbgI6VM9IjRywtygd9rB8LVKpsaa4kCvN3EXh5wFE2/gXaWxY1yHvveSCN0EoWS3goMs4TexyhE+OFQSqJVM8pr02V2reXy3mnJUYRNaYtN,iv:S9uwVwKthMjPnHljb4ClgOkECYEV1IYZPQpm1Wr4mnY=,tag:HOhpF65au2sl00GG+KTuYA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUGdmM1NiYUd3R0FXbzQw
            Zlk2YjBoZGZWQTRrUDE1NFZZcG50Yk1tK0hJClRySHk5MEFSbkNOUmNOL3RzaThP
            dkVxbTNKZkZVOXI1VlRNQk9Wems3YWMKLS0tIHFRcnZDR0ZOT01VSkhhdTVGb0M0
            WnJaRUpaWGpVekg0emVjVW81OW1ROVUKRs3Smn+ECpNk1WcuU4ECjlKhvowUS3TI
            hVSUNEl7s4fSduD/kbyDcTAos2AKGkaFU4C2L31Cl3riBtRoVZOM7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T20:53:47Z"
    mac: ENC[AES256_GCM,data:FN+tSmulQm5wPEgm1hu5AYhGoI8ZSeS2GfVaCwUcR54mjdzrx9eWm8ZKbRiOa8XnUqSBO+c7/ufMR8+sa/G1Z7SXe8aPcU86Z+zKZ2g7y8/eHwgtcXizzE1YLGwQrBMqXmUG+CW9AQFZNP0f0oMF2MHNtO01NLB+3m3UWUZ3xIs=,iv:tWjyHraf+ywBiuA/deJsm086NtVNPlQxWa8Dq2B5Y/E=,tag:KosFLoWAulgxPomoiRXxew==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
