apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iv7JKUwAwU2kqKxW4+qUdKz7BdP6V3gjJ+wV6FFcBy1IzCJANNyUtyG/X6QAANY+y+k62pkh1FqPR1HXqsB49JlQogpl4oOukgEO0mhUUkJyqxdt/Cz698tv1WQh7n8uSYwGq4mxcuQox7eWoq0MmI98/YphvgRvpsVFCHJOHwnvhktT5p71aa68jTtCnXiUM8Ens3PMc6XCEzEwBOFm4Gvlf40JYD1E1E5uUmDY24y6Cye7fcVXIKY75LUt8td9CEoIxirQ5rZWRnIJMFlkcgY/2Vxw4QMkG2cYrHrOLedYF8uJ0HKWvhFlOA4+EVYwH+Lkx4dlITGESQWdndjJ4mQ+kUbnX1eJzifH3IAvLy4VuS5DWLPSB1njzqOybI6+,iv:IlBOooOVgAybdilGd18XRJeWpuJWWH7a/KP3PZKkMUI=,tag:Z+3ZzT2AzfbrF9/uUw/bug==,type:str]
    identity.pub: ENC[AES256_GCM,data:Jc9PlMsjUuxEL6nJMAD2QUy0ze0njIzG1S2rymHKXYojLd2r0l8qiGUOwoWvpys95DFX0Az39P5+0+QIKCicJ/3IfSj6/Ke9Zl5Swv83RCcySA8EKh2yvVd26ycLPRrya1ssULy7XB8uoaMHxZ4EywHHPz7LTfaN8owQfjvahnSBWetDDzIx0E3vxpRSL9/XUtwX7N1jAR1WSFrZKD+f8KUFouusLU8CGr0CA6PWRjhWSBIZ1rKG6G77BztVXV+8m9TsMaaSrqBhBOUpmw==,iv:Nd0AS7sfGc6UuJlPm+xrB9gXVYRxl1VZfVDZBXfy8ls=,tag:4xJdZsuPsWfLXJj5h+ypTg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TxIcCWycWxg8nF0Z+TNbF/JDMteGHVWiIjiNeYoxJ3Gz2L8VAnnVQVuQqxWUcbFfTPmyohzLTCnvekAS4SrVYaDAHeqdeze6atdXJ9LiZe/OW9GMlRpaAtvPCKxT6eZIqMefeffC406uLVTV+CIBiz3FAWcPm4zto0L5dCgiGLN4DU47udO3M7NI2sqDVY01Sjeeu86d/zkQbVQfPZJwDYcTA8kNhvL47JWT,iv:sIER0qHl9W6QLfOawiRZqBVs4AtAjL4bUoPRaDJMtW0=,tag:CR18dSP+dpnFpuRmcqfniA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZUZ4TmlzNmR0bjJGbmZS
            R0ZzM29KRGt6VTFyN1ZVK2prWXpYQXpzZm1zCjJ0aHg4QlZoRWtGdkh6dW0xUjcv
            d2I2V2RKUmpKakJEV0JVSHc0MmhpaDgKLS0tIEMvRUNaSmJQVmJ1b0pMYVlJTWpk
            blZhZC9Fb2swTUJxTzRmRWhDMEZGZ1UKwzM695+aavS4j/aIkEEP/B0bAup1fAUk
            mknYaoOgLtI+0B+gvpx9T6tFKjwxrJbrE62FTDXl1G+G7NJhTyXVxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T02:20:26Z"
    mac: ENC[AES256_GCM,data:kpZeK51K8zZNpn/z6jR67y/ZCbVVMsi+y7MNo6jLc8dghhyC+qqu7N2MoJj8Nzuc1Ry34Lczbx/J1e2DMsP2hrBi3cFTvnm/JGIWFaUchaGq8rGH5vtk0ctYXEpZP/9dY2A52+LgNToIvbv6RmvNJg5yDHzxasJRXLNJytaJbeQ=,iv:1STDDz7vMBYsGiCgixscWRXRITWHOmwSp48WxTNiBNg=,tag:nEdoGLnu0Cp2eI5eAfYYQw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
