apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OSOtQ5L+ghIdMhtNj7dNf22RwTN0xBswur7+G+8cc0E9Y2EsQPjfKzyxh4hq8kflDGDe8cqteLRhoaS8uDXq0+mA98na7RO9bZQDSDx73/nuI9ZyQbYFHxPIxpGbG78O5ofM836/VsOheUHj7IunrcfGdbK3VKrW5MBUA/Aqv5J8933uGohehjtkIvj5/ySCHLEAY4leus0pJZfk7Yq+37IjCyhz+oCinbRXfVCv9Bi6R2lkPALLNG3fDG5AUVBpnrcMVZCEe0mdeeZ6M/aVre3k8XTxX6oUYm+/vsXPGZLtgJ8YFSxIHt/5+/lfABE2bLMyl4RTWlL3kOAwC9Z8VVOhoNDw6Z2Hd9drM4UqeSN0SXmV4dkCi7MBfIRr3oze,iv:A7dQ3eyxjS9vcw9CeBFKqGaMUZjFfVxFbwNamKipm2A=,tag:EW5CaZc9OlP9qZnlibqDNA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tqDoQ8Xu8o3owRWTkdRAb+QnALutYROEokBqoYLc5cFMTlLPZ/DQqrlOJaCD0oVP0aJR1mUBQ5b5zp6AZeqdUbaNS/dsEmbYpPH9R7prk5Snu67cFCzDc7d1e+2VL9Q/q9DJaWt6fGxr3w5bZ5Px556Xn/nO5Nekf80Kq8DDvmJ0I79Q5HMoBN7ec4TvmMJOmOgBStzeTaj9jb8V/QrgF/ItGKsh5dp5rpWn/XMYHbt/ttG7Olk8cH17fTm6KM1iz+LU/qWk+xKABoMezQ==,iv:NDCK0B5yt/D+lPxiUGihNhJ4elWGUuVK6A2O+IMMq0g=,tag:ILk4AXpWd23LGjy1oNrllQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:qf9meyQhBKbjVYmF3xuSQDiR22RMMyZ1l0sHd/KgfgaV9sD0KwowZ8vXcOkOsxRpKeaI3SYogpx8uEDvYkzI3dbxmDxv9dUgiDktN8GFI6iSnxP5w1zkEU84A+y+x/zXEs5aucQPAbKOSZ1+l6JuME47Pae5DjnzSikhbnQw2j67B087BxSDg+aWKymhBXo9X0cd9vZp+ZxF00hjUjMyi34G1mLS2qgozLxJ,iv:nkVPFQ7hSRSTMt8FXHIUMzjkAgY8nptJIwVujYG9J2M=,tag:y6xlCofU8WdDgkKGqASSDQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVGdpVmNLZzloTTdjZlg1
            cStzUkJpVTlWa05LMURuTVB3ZWdQeGFGQ0dVCjRmTmVmeEtielZmZ3dkdG1UNys2
            dEdKYkRHSytFL2MvY1dFazNkUUNzWUEKLS0tIFA3YXN5Z3o3dFVBb3lrRU1yanNv
            RU5DT1dQUVo4WkhkZzE3U0k2M0J5TmMKVD3NGtWlcE714I+tmhIQSUGa9GIECZDr
            7evWNg3c7eoO4yon0pXwo2lkMjmIgdVmVEdeoCysXaGn4kFiz9qSbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T21:20:16Z"
    mac: ENC[AES256_GCM,data:rOAk4LwIzDf2oB040sm0lbHAb61xdpYOKi/ifJOxEC0Jkah4g2OrawEAWiLPITgUjjZ7eMd+scJZu6W3ZckF7+4kgJHwh5vAWDx4YzW47PGuiVqqIF+hNVI9/f88TjieEe9HoI3rgTTrrxilCF/wQ2pGudwK94DdZAwXOb6U4IY=,iv:ZDWKUEK3xDaqL/jcK8lfBTM/mGEIf/DhaCZwqvDH4zo=,tag:8TJNdzlIkh2b421b3biRew==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
