apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SdtfyxBF+emRKGcW/f/UVOzXSKCQnA8ldUR8FUL1CNDh/tTqEranIqjhU9WZFP7kBhFoV+bTOpRCvZtF5kp29Y319F2XQqPCiY5dN2Arsm2dF7sUanTWQnsUvmFKG9FNSz4F0AfN4N8H8dYda6dUUmf059wRXoN6z2kzWZWykqjtwMjFJP8b3UF9IxRfrAEktX1EdMrCCBVoyMl5xAox6qHHOwxg74fasFRS2qL4PU0LEyGNToMLs1JXMRV5U5X6p2+BFCs7EJriKM+nJHimHWbO9WgfsXE2b8ghx9QVNDcAZoQfXwIqKbgZTqJzdesoy83vFQz+Eh5F3CJIo43+c2iuhYlOAhFiJArzF6+0t6b3EbQ1ni/7M8OUW3tcdIF4,iv:GC2+w1NRBbbMgVY/PZU5Yg/4D7SZ2BTacPFK5RfkVtU=,tag:A7FLV/qh1ljEWQ5poQ3uEg==,type:str]
    identity.pub: ENC[AES256_GCM,data:6oMC66Xxf+UYpVBZfpC6xSrFf3iSM5Bp4LpDUh+bAsrh/oA4/zSOqJqFg87Zvb6kijuAJDO42yiSkn04s1enL9doHrtGcbNHBl6bVqe0c8m/W1vtfdZCWUHZIwAWL6h6990HjntvqPHnouUer6Jf7exFidn+YO89VXc7pViVfJjh+qmcuLfSddVzE88pQKeRCj9A+S+iJqkM0eDmUcd3cVCUP4/xjPGyIvhDJgs/n4pqmqNbRUJDsebLJ78SoOAmee4CYfdpsbcF3arpXQ==,iv:y9gdr9d7ci0vcrqHYktfpWZeH1heO0DGHs9QV0AbamQ=,tag:wL5q5CsrUjheZKyV8IOBcg==,type:str]
    known_hosts: ENC[AES256_GCM,data:pPPYhGuTMBibaJ+ojTJhycf2BRBEgXzepf1/98CEc2U3MiSL/OtYA6YjsYkKdIm+aHrX0V30iwAOex9LBPTwQnv/O3ZGj2JvsUY1B11zoXiN9srEXxYDnl4NUK2rNsD3cVaSX3z+GLDr0S20vipj8nnyksBTnLsxmzo5+ODMs9dc9EFawrVz9fjlpj4/0TY2AldUARAr7fV7+4gcV/EMZlqr7WLDK0nLRl72,iv:PmeYuWuxyo8ayd1DuEeb9IvsR1pG7JebGi7PaizYeiE=,tag:9yijPcZmLddxe5eJ1WwbBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6ht4sfzlt8xsg7rh6rddfvtg8meqj25feg2h7h57vgf7gnksyfs539xq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOXkyTEpVdUoyVi84c3p4
            WEZtZnd1RnlQTTRTZkNwVmZwem1SUXYrNEVrClFOMmFUaTlWS1ZIbi9jZXQvVEpW
            dFM4aUNOQkE3cDQvRDFxa0tFYUhCV0EKLS0tIGNWK0hlU2U1dXpvY1J3V0JUbDcz
            bGpaQldSSWZkTnRUcVJJRzdKc3h1KzAKBRhUPbQZXGP/SE2RivVJ1om3rOvN8e6O
            qy0ImjlRZWnpO2BNxST/xISOj7d/Nz1vmH8zZ1AXZ18H+ivew4gvAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T17:46:06Z"
    mac: ENC[AES256_GCM,data:0OPPnq8X/bpO2PUjyW7dXAQuHjhIj98G/AE7eM0o/35Zc99tmMPIwZ7mQirwjXwP4RdyP+csYmYZW6wDMneP3/bMzHWitdgQFoorwnMa9latkQ1Ta0GZdzN+NhE7rhFjENSlXJhsVTq9nquedRLqR8x2jXK3yMQIIncx9g0CmbM=,iv:FXywjajFSEFoo2w5GxmbqP8jnvfjtrMk6gE2XEXv8Ak=,tag:B/L6LCi1HRYPm68z1PykrA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
