apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UmF/9zglbTRisEV7v2Yn8TAqO/+BArcrz1EBRia4n72TEAoHsH/LaeYKddT6sE9Avp86nU4YIprh9eaTy9OILzpEd8rCoJR9d2ar7jykftE79K9lq8tNu2kvF7AX/NVL7iwLeJK2W3TFSSrTmROr1zDFodRoorBN0fSlKIdqHZum/B2KNdmcUFgaL96CQtBzF83O1bA42XvlAlEh25eXZ0al5gkiK4Vw34VxSH1CFL3aG2VQcJ8CJpUieBWJp1Z+S9Pa3MzS9AwIN6zIxrbFtrYyw8DFaVwqNl7FacLfVghCHU3cOh7WgVrhGBadnIiUFOn+Wh20HV1zc3Z79OtY+YpJ3FwVb+ZzIkist3zzEeJq4N7ExO+dDAcJMWUiGSrL,iv:redTi36DzElmdWUHo4BLYmu5qLonEpGpOKtqM34o8yk=,tag:XCooWQt/Va1LXHC295hlig==,type:str]
    identity.pub: ENC[AES256_GCM,data:pGuuigr3dm/0d7r7JCkeEbAI2WTcoPp9Jig/MM3aeca1M3ey1mQwZZK/2BL7SvlZ7qzxr9poa7keKycPD1oB8zejE/16NLwUuQvaBgI/5LtHZ3e8d387OKzkx0NAvq0d4we8mAYfl/Byhnjlmos+PzO1Url9c9XxYW6TEGQi+Oeif/Qbi+X8QgjMSSIZ7Ou1UoxVxYRAZv/GzSRWG4yfhbRzlzMRpdvD4tu8qo/owNF9VTbhB8c6hYfx0mQYx1NWY7R8JULO5W/N438CeQ==,iv:Q7x+G/UMLWd349QYu9MQJt013tKNNP5oUrGmt6xD774=,tag:dfatbSjRlub+NvwIcEXkIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:6mdeLbJ9NfPlSGfc5oBR3rojcYlH5rNan3NQ4n93OSGTsh21ncJsx8GmazQ/DAZv5h+jL4mQKFHQ7tZFLlF4wGLDSa3bSIKc24LJEFwC5RxQNtB7ulVqVW7JAd64gxqWbcW9XXMH9Ev0JijymX4m1FsaqmGXX5OeNhBqiVXUNreLZBCDS/hm1XUdU/s0z7LnkfN1Bt538DA0zn8u42/0oBctzN/zaEYu6pFd,iv:klVQlOGgp37PytTpS/YEDNK1Pep9qY7WDFuBK7GghfU=,tag:2lekdCOg+MxDC7kcDsPb7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1450t7kgj6ns5pflgng9fuyn96nffs6svfy7ssx37v4qthkjesezqrxrzn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VU9zcWhyRjRZTkxWZmtt
            VTYxc0t0WFlhRG1uTDQzQjV0UVBVbHBRWFVjCkhaMVhYNHlBZVIxMmNaUlk0K2RI
            R3NmUlVwYzV2RHhQVFhBNVZCQ2J4Z2MKLS0tIHArZktRVG00RjhtLzc0L2J6aTdk
            R082OWNDR3ZWTzRCSHNmWmdGdEhka0UKvwuCgMOEUcAWnDQueFVeZZ+rAuz0MumN
            Zm7RJT46nMshWIb+osGmsNRUICQi8JgJ6s2pmosa1AeGlX+Q45MxHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T21:44:00Z"
    mac: ENC[AES256_GCM,data:BZ5MI/x5ihf9fThOfWbtbsGCDLded8T2LlhJVgLwM+YBtTt4Z33Y67cBXPJAqZKVNpmOPQuY5ARhdAFDV47gSQCJ5dhFDuRV+GuNyhoXyZtcIiwEznl6X2o7PMTc+kVX5GUQTmrmgKoQvLXNIpuS4DutTBM024T/ilrhfZ2+45o=,iv:R/M8oWpG6NnJIpffTh1eRnBi5nYBSdpjnEocOR6No+8=,tag:iykFTs7Vx+ZoIsgTdTTi3g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
