apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XVz0Uxl9Btf6ObGDNLrgQwoPxdSf2J3prKy/4bFx2glmgngNsbY8TN8zsJi4b/saBs4m06ZRe6JFZgWhjTbLFFa3cEgfdCV9sQgsUY9fZGda3zYt0yT86kd6zS1G5FrpdRK1b/WgP9JDiaArw7qfSaIoostaSjfthQ8DMLiveSrnIdqRJZ8ind+A32U2FPE29Ie0uLcV2TjyZbZgr3vI6LDDPQ1pV86so4x2NtpK/43XGmRuQN/2VyAEHzC8Y6l50dl703zcvDG/6fDYutMKtUpbBb+bVT5OBIBl1G4hd8aDBIhAlpUXgzgEyKc32F3N8igT5JPgsKVNPfpaMtUnd94lnJpSWmGh7TOWUv/jAA6k8L8UR/sRTtrnIk5nlaGI,iv:HBz7aB9ULPIh1B81NVOajfS8ItbrzTHwUkFz79ROs9Q=,tag:N8k7N2sGXLI3wKkCRWL6DQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rc7zl0BSx+FGbkG/yh6xIvUoY3jaIcDo6n9IxBkL5UbHulXOlFSKAXPT59z8Sh+TV+oujPJRSDaBHhZRkqdGE6R3wJWmUHq8M6BME9soAucqpm6qgQ0nCc/NgpZBHlXoBTuBHVd38+H7z1BymIlw6nsX0KCW+0R7yDLSeeD7ca8KNZ0cpuTLQmahBt15omvIIQxgWL+S7XvjDX30J1MbDzdYTAJQTs8R8Qd513Tz7MbkzXv6xlm2wTrLeYAMGThaPg4FVkV4JKeZ0NTAXg==,iv:qbDC8cZAVi6sZlwlc2sNFhpF4fxIVqf8erPLY2lt4tM=,tag:yXePcdZNVQPLGiw3zKiLFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yXZOBg8xkUcQQdyJY9hOtgf246QZD/yPnhrVaTR/xjoMytXpVSMyHZXoKWM96iTwn+l4Dc4V1Cj/PuPmxGSmIPCk5DH3Gx5FdEcYIy86h7gXAMufi8jQn0kQKkXr/v7AIC4g6PSuthPofNDNeZfoNogeCyGZobxJzOkLY710OT76z/zpvbnJxOA7mIdbfzjn1fxJ6AZpRBG54QssPg0FGqURHC9jzRkXo4HE,iv:w2S0yxbMoSuRsidSsZeFb/bqJDZ3J7S8a2SwQwVjcQo=,tag:j8WLlpHVKPjexI36hxlfXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1450t7kgj6ns5pflgng9fuyn96nffs6svfy7ssx37v4qthkjesezqrxrzn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U2NPcTl0Ui9RSGVCNjJp
            VEZudUhBUGxjd0JJYkpnbGswR053bUpaMUZZClZCNWc0am4wZjhnZ0lYOGxRdjRP
            UkQ0TlBlOG1zdUxKdUp4WERkV3dkQUEKLS0tIHBGQXlaTkVZSzJwNFJlTDVhRU0r
            M3RtQWswMW1NSCtCOXVSUlNyL0U3alEKyBAlE1N9y+mNKrlKQQ7l506loMuRzrZT
            uQqHoDilYHKn55OMJDJGSy88sD55b8/zMTmOOq30FystnFEPCQws4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T18:53:21Z"
    mac: ENC[AES256_GCM,data:1mFhsIc/SFvmep4XYIUXF6Fe+7/71vkxwWOhJXNSol9fzTUhj8+2M3mng5topQeX6YuF8LDH4drARvBEL0nexjSnFXmPsJ2zAbCBwutfLMunAMiVrFKb0AEh02WALFynkQMtyhLlckqvMlwv4L9agccAcRD1iaj9hlNOp9dNbXA=,iv:KxkhumVN4nRZsJ1pf3fQ0yTGdAXWb8EH+P5BD5of/rQ=,tag:AojXR3VqoinzmtFqlLhwKA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
