apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hLaMfBGnCG5NdTd4CL//ym0NSWj7wNxghpoIDD6tN10BOWKncwYYmPT4PpecgYto+VuRy27VNu9ZQ782mYfd9Ug7/LpkOOsEEiNeW1qinF0y7TQ7grRHt427KtNSFVQKMdOJ31tmLecEMTiYC9PWVEn0NR5E8FCm5Ir8CcALEi55m0mxmJ6s8g/8O1ZQPR5aUxGZYpkinr2hyysRoXkASmd22gqnmWhw5fknKAiud3KxentRJR0MUHqBgtxKHP7T8HIz0ZDVrT7mnWr9nDveHjqBs5tJx5VTuQC/wYqXidLVoU4gGvXAtXw7YKW14bYcV5Bcx3xr/5NqLLiMIRNss6NI4nR9ci0GYPIrpBWnQ0/up6R8GPeU4FMTrmIG4w6m,iv:FCujDNSL+f4vS5/LbzBzGdC0rWZhWtyEWoKEIV0+9dc=,tag:+Ze/d5WtpcrDpzltx8dqHw==,type:str]
    identity.pub: ENC[AES256_GCM,data:R/Fyz9Y0/8RQp7aLXTsrQH/YTB/xUfdn9KLcjlzOOOZISg+WmQAQA/5vQCGBxcJG2Wk9mMoAmkBca2lSI2Sy3Qni6f1UtQlq8yFPAkibv0DHQyeVMxJ6EcWb8RCde5aM+scqiI7Q/e3Ua4G2ug5gMyc05CYZM8lz45j3wh5xszmejdyMhPRcmyCBNsSUJMDb+byURIz7OYJS0KRyx8e8ScRWW3gSGjQNzOGzKZ4Qk6swXv7+4NxrWdGJFgcvKGHnxWC5w/7A4MkSlbP/zA==,iv:ppMFJA1n1gtxdgCXE2f43ruZn+hwYKZS9cnhV/V5ssA=,tag:ZSnvpL1nuuqPrE2rRaI4jQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:04FWT3Ypc1saS4EtnBL0mNOJUh/qaHzmGzBJQz0UlbIgUNBZD/LPB9GAaIcixCbzyo4AvhQUsi+iC977xTATRe0uzxj1SU9c7RVk5FC3kfZoieI4QZwGFsaW0vtBv1tIfpqRq6DL98/9dIX/za6E92JOnPk7M/FnTdRaFXGVuO+I609o44z8TBwkpf00xHk4C0EDPvbgzc04RfXVlJ/Dk9O8HoxV7XCkxzeU,iv:otdKZRyj+bmvK0NnUCaOR2fBaWsXnTKVB3BZqe2o8Eg=,tag:34MOogobJmOEVuC85K5zkg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RFRuQmlGVlI4NkVPMTJK
            NU1SU2wwNm1ZNDBhTWtXb01ZbGNBTzE3aFhvCnhWQlM5dC9ocG1qMHRnL2RFYjJO
            Wk1zQUVtUmw0QS9icm1NSkF5WWdjQmsKLS0tIElDQzRqVVR1b2k5bCtOVDV4eEdQ
            bEJITGM5aGw0Z0duMytmLzBCV09CWU0KPOXFI1GUb24/TzpjmR1waWSk+GKG+7gm
            ey0WqR5ToR+JdkKhMc+2TYP1MjeTtPrrYDl+0sBPqA8FWwl5zrgT/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T14:15:31Z"
    mac: ENC[AES256_GCM,data:qWTWjQD+3DmbNBLqrRqT+VrVgsWnuZmSZjLylw0ztG8TMjwKfMcEHPvwdkyaKFYOPmi1GRUk3mQO0WjC9jQyhtVt+gDUkPBtwmuC+GiIpVlosGXIzV7puYHMrGvGyW7Vs/d/ztbxQ7RvlcyWLogFiMsMOvPfcwvzNwi2RDoBpAg=,iv:ZGBwI47e+h0eY8V6WcxrxuQ5WHYUmA+rpP85AasKLk4=,tag:QNrJe3cCrTrCbaEVDD9Tvg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
