apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gxL2qMS5v2rrHc9y/xCXXbkFIjtMaKLzuObp/3Pxwbs3NlsadSRsDubngw6pHkf9LA2oEnV1Ss8YwDJb3/u3FeLOvJGlekk0o3PsIJCUF9V2X8mvIfYFEIpgU2s+WBDkyQU9IbHufuIlslGL3itqZNhhZ7vQY/3K7BmOQSWf7JWzd/lWFuUu1vjNEK2rK10LUpBSktGUfCv3SvkTCpzmzSfWoSWcyGUjtouFwI41Idy/E/RJ1acJJWqbCLAOk+DXDhUdb7PjMvtFlERvIuejU/QgAJiFHiGQIbKAZhLMrdUpioPlYxswt7ofELpoCNmF/M12ZWWhWLdr59Y21qxlMqLO671PfyVQJVLgbJ8xLJZ4sxjPxbGxoW0yMXKbDtdQ,iv:DGARFOVOT3t0XFU/EfRnPPNg7gkvGo+uxHo5CBnNKSw=,tag:RIMD/2NdlqXhCrKX7t5PvA==,type:str]
    identity.pub: ENC[AES256_GCM,data:KHCaxzxLmkd3bmcZ0a3MsVmcvFF3gJNSYH/6jsSTsRjHFOb7ajRMSuaN+m+1jTTNngMZpxGTXz0z5Qej72uOFnz58azhXS8X77YklhJrtTMhiLyDvDlSBettNh/H1+eVvVaDodKc7JvEFecUgsaL2uRtFRuMQb4SJ/hU5R24wTE8x9R+OOC48um9RTtQ85DD4QhWY6NATYtRaC33exWjI8a9r4rLZFCCLZdcN2xS36J4yHzb1FSTnr/VxFbkXJwT9PXrObJhYVK2BN9Q0Q==,iv:nmo+14xF/wPo9O8ZcmWbbO8DsUtX+RBSjtvTRYzNzls=,tag:QOIUbsE3HWLhjd8ST+qrpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:evfvp59xh89SwlDSKtI6vlsz8DSNJFKfQYSw4bVZyS2+7mx79nh3vwp0RYpQLo0ZUEqgrUDFUxWH58R0SCxZ8aBsCGndhxQY8qouPFgt4fZAqaeGqO2dr6PQozYX9ecD4sXKQOScNz0onCqbd7uewxzfgaOFyrnzZdQFdqcNXhm+TNdbOA9UdyodU2at6Vjy+66xzETTdKEODR437uaZJ7OuCQcVHIShHkk2,iv:QXXKL6ljrhtsj6Ln+SNiunHFPdkfMYf1q8jzCpFpeG0=,tag:JpzUNnU7KQTtkT0lQ+WclQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1450t7kgj6ns5pflgng9fuyn96nffs6svfy7ssx37v4qthkjesezqrxrzn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWFpqeFc0T1NDOE83bEg0
            QTJYakRjbGNrcGNPU0xZZjZnbThaL05oa2pzCk9QcTZlNmVWNDJqaU12VllVTWMw
            SjBuNzZWSkxRQmttb1RJMFJ3cVlWd2sKLS0tIDVsbVQ4dW5CMUt3elRETU03Yisr
            QWM5T3oyN0VhRU1zdm5rTFp3VHgyeFEKju9nxj5pXTSKYFTVPUHCadEURb2/32/A
            NbzQnAP/6aLE6Ppz3s2gq1VfHrlm/0hSBc6piTQIqoL6MdiDr9NXAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T15:57:40Z"
    mac: ENC[AES256_GCM,data:7/S8lz5lhgUPgJfb/x5xck1no8nZTKeMK2sPqp8AE7zQgjEWoeO1rCaIiSxeHNYcZIQlBu2rsBRqvJ55d3jev2OOegEbmsO+Xe8qDysVCLr0W41kfNsMK3dNWgBnJSSZzsKANGH4RA4wAXX+B0fFFwJX2dpvotoR3ZipM3Agw8c=,iv:kBxIUB/lTSvu0QyNxMePZTfl5FW6QuL5O5htLz6gnFw=,tag:3sc6feakzSByLVE4BpYD2w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
