apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fqtuLUCNCw+wVh2/hoEI7gt+7Dr/AeKVs/2pb2UBIf5mZy6bEsQHcU7jX1xrqnOAtsZrvXzf2CWRNLB+jzWiacWFNL6Upxh1n2iHO9/KkbdyWR2TQff8KV5W5bZ1eb11M9s8yPv0Lm5jv5ON4aFYw/4KlxODvvu5R2ubdJObKrFTEioT7+PYqv3hGMqioXqhle71bN34pRRS4l5TgkNhWf6zflt5PA0p5X0yANn/oDCFM+76BlU3iu5jZbKEZ7iVRc31rCNFdClDtAJl0APIupRH0j0JTclITU9zhSSsw4WTULJ1NPo2rwCfpDnEzfqxCogLJtcHngw/crtqS6lzxQFoA6fhymqBlHfc0BgkMB2cw96Z9aSB2gWPSjzeYXJm,iv:MzcsQ5J1QjdoJtJD6w6YyLULofczuzvjQDCMyIA+2lk=,tag:7/IBwvmEHEOLBO+xxUyeQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:RUs4gn8DHnqZXo+esYzr+J6K2xzFCAOhTtbdPYs3TLBf0u1qlHeZTxKbBME2OMuzFdmW/FIgnMmN0BdL3CGfpdEoSPEehuJiIXZXU38OB2zxxuSBfoX20ZOCDpf6dFG92nA5R84X9I1kxecCdUsyQhNR/dYnO1j/7Fi43BEhEaGQcfyKK/JvK+oyuKq1aK4y/MfGqOs2lBWcouosGagXQlnm9PCEZ8KASI5PJx5mhamQYPZOsGFySVOHGv1dRVjsc7qc4fht/8giZzyzQQ==,iv:mffE0zHAnHDnjaS3hoL5TlcbjPGWai0+V1AgkIJpkb0=,tag:PhpPCaOVdoo3N0bCux/x/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:3684qSEdqhroW97ztoG7VnKmVge+qo+MK2z5OAvNWRQxOjx8jbHjDXH6uIA841ZLp8gEODJFoJi7XSsgZCFhuZOt5drF75q1GwmsTQ53jV7YpUBBTGFvnmLKAzrNCSk7NAcMopWGmXobCMklY8g1nXEJ2Ur67bc5EGGSD2ua4oh3RhjwzWjODJEmiptB3S+AODcR4bEGsxdv0vd+Aed/5XCg4tksNLGr9rgT,iv:BQi9b9G1CoX9DEF1Bs8TO4cbYpF8ogYmk1mDA+h9xwU=,tag:J10vx0RTQDnPJW3jdLMoJw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1450t7kgj6ns5pflgng9fuyn96nffs6svfy7ssx37v4qthkjesezqrxrzn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweHJ1WlZ1TjJzbUJjdmd4
            eE45Qkl2c1llKzlhbWNIcEZBaU5aNFdwTGtVCjBLSXJyTUJJZjhOcEJLS0F4S1Fi
            TmdacmlxNmRnOVRXODZXTVZaekNobVUKLS0tIFB5SkRVdWZhajhNWnptbUM1YVBv
            OGNRUi9OQWVHYVg0WllxeTVkbUVOR0kKYyzJhErxjuYY39L/8kdmlCurfV0NiOvG
            DrYe9Dvda1sbcYInOhIrEh9C1+q/eXiesaMHq9GSk75mXmepS0P9YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T14:42:27Z"
    mac: ENC[AES256_GCM,data:V72zxnn5qjqcjTwXzjW4RrpteJq2E0+/fyb+zC7j2NRWntpr8/Kr4vIW6Et6KxwNs6lsATkh1ERTKrfUuDBIBKuk4Xy3C0kYNinn8TAHrC3Wx6TJAOR5XgBnAFQGcjYH/MpeFlz2TXCjgBnBDzu5LA52Lt3u3AQQIm50LHaLfzo=,iv:RLRVonNzN7+kFyNodAp8tpXA2dIgT5s5kcUPeBHGeIU=,tag:g55sqi3hi0ugPEwOPS6QyA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
