apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RB2l9gc7Nu9Er2LVmAosQBi5wkRg2INbswRN5mDkaOvUt1ctEtr0+rWuG53KjjWca122wkS7pJX2dVGVtiCs6rjJc7avN5PUNLS693NF5BHGEoUlqXKNVo/WMtsYyZORpiNrMFQMj3cK3Npp6XPz6r4bZvtStnx2C44oLvTTnCW5l7JYuhWDBaHs3J7tTe8T9rBdvt1mNtLo3sBm8SXOeDvvUNgmTU+g05pgSozKmn8AIHIk/cA6y6NufmceQI59KsoDneAjx25Gl6PuzEXfDauCeJW99+dYkNwj03yqrgb5+YnH2awgAee2ajOxRSqAI7HP/1/5nGyjH7B6NUJzuP7j8xjiHhrLnWTP8QziCpgARotw2sG3TD6b4qVX4FaH,iv:u+xWzHiKgV5G5dpGDqNV+6q0yJmngoiqJDUnADXl7n0=,tag:7/i/YMzzpNynWJgNXOEp1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:OVuv0gGxv6cNgZmIyPvb7wJzh3tfNbsbjyoronCYye6CArw9JH37jzUSw2X50sOLMKANFswTfS9wdDm3IaJ5fiHjFTBoOUMuxdIUxdpkMnQDim6iICq9Tq5LNW34Ul7kjKWSI4rdh+02Eb9yorRuCbFil4T6rRZTJp94p848n8RLEnGosy2QttxsagCvEl7tYHg7AZkLXgZvHV7XGFwCPl6s/Lklg9LVUwO1CidSUOzb2YoEYbTNiPD8zTKZBd7OfVCyGrhCxJeBcrTPfQ==,iv:C6N1T155v6uNplMJNAecGf5kXe933/zEy4aRmEeTiFE=,tag:jYZUxALgBvI9VRKTu3DYxQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+x1dQOIBO1s2CMMUnHeWgPKHNdpSMhE1boJxPkYoZcvcOe3tM0flQ8Hh9FLSrej36U6izTAs7ING4TLCUZ8rqvn5fO81wk/zXXJ+oufQY7WRT6Irbi1Y6VLhJhe77u1wwqAJxZQULePX8uKEJTseYzPhibMqjDn5LKsrVtrqJ4PxrAgA35yiyNWzEx2ks+8stqyCPlsv3mhOkj1Y/Fe7jx5kewSGhoGeqGnC,iv:jWQibbpeNxDz/un84znoW5cGKweXkbUBuk+sZIC4tmY=,tag:xsWmXvkduvCHU4VF297flg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bFhzK0wvU054UXFMdHQ2
            eDB6eEtJTEdkZGkxSGQzYk1XOTdRRjdGeDJJCmgzTUJsNjgxajJaWldJSUJuRHVu
            OHZmZDNob3Q5MlZkUjJaTWNJbGFWSTQKLS0tIEFWMUh4aFlJQ0d6NXpHOUhBU2tQ
            ZnNSa2gxVjRmblYweWlrNlhSaFV3djAKWR/QG7bc+BOePrUbq7nkP3mlyirmogYx
            IIL7HSLBh+5lC+ln0rhIXtnu5sFY3hFeOmXPbskzNKtZWgSa7VHRTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T02:37:39Z"
    mac: ENC[AES256_GCM,data:f3aYrput2srhk028mcIfuEL7D0gTbdQmMiFyz0Skc8CxXRsPY35pwSojc+T6jELxJXQdoQ0rYsGNnJQ4EoDONCPOqy/5gScDRVhPPgMoqi7GywJ1lLiVCpJaJFFteFi7I5HHIbZCn4OD5xy+JTy9fxWx+VdB6F+R7VFVbikauiU=,iv:CnhTsy2uDI9hLIpVuLUZESvI0DpqhWA2woUiXk1k8Vg=,tag:nCrC3PMKFjdYUyDXs6qIMw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
