apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:u1bZYR1gHYHCvXngoWm7k3u4JZfOh0X+7BR71+A4xQYGDydl5J4L9iCl/td9V8Vvvv2OpbexXQAfOARiCMG/hke7gaTC7ZhaqF2VSjFeI0zikyI7yW0zjJERUS690q6qDg24BJum5OEmJvs2HaVQLQJbRCl37/lFC0v+AAKkZEv7CfzBsnH4OhgqfbMKnfFO8jAI93Ar+aS9YnxdMNwX5DB+0tSfllfMNXCjHrVLgl3UtIBCeSsHElfEnyWkxAY9fZzP3B3qAZqSfsmhKQyDPnyYrfJcqM4G/UFDKkUU28BGFh4ymkVdGWwgvjk/qyaXIJnpFjTIwt11bxe7NOFzBON/05xfEmvpsBR1DF8Bwo6TKeK7nWvTQMUFQu+liOsD,iv:AgrKMvMrV/qmUEhWOhO/gWicYZr9ikCIJLq1SBDjeNQ=,tag:ryOPV7a1CTlzXK3+FP8CPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:HTdUwIwdaNRoUvK95CRG3t+Xu7eBpzeE044B6tpWRJWT1ea6BDUcBFdRFzkdSO+k1Eewv5hn0c6+iaQKdP/7fVY8MPqTUs0/uH7q3LXMl+QSB01BYlh++lJ5euW5kuikqV87wvdTKFmITtTVSgnjStTctyE3EphmXPwMU8+ICGlTicQWrN8ias/HLGJr0D/Xb0pzZR6xwfPbPxgN9tUxaN2MpguWoVswSVbDBnQD8o6wtvLxo06G3EEKMqWjM5HAbxDOezEOs9dpxH6Jzw==,iv:TXRF2TZcvaZu4SkYNBTC9Mny0SQ5zMobL9w5N/TPyJM=,tag:zshRTXUitzqIr+2l3om9lA==,type:str]
    known_hosts: ENC[AES256_GCM,data:5Yx0TnIh4H8q90I8dr/TMI9bxpxLGeiHeNN2dbEJQfUc1wDqAr1H/hDxiC2E3bPBkYRJxgSGax3dCijBsjuwKy9SXcSkwSbHiVsRFrodtj43h9660Zyit4w3BWG7VaKh4aPo4RPZJ0A6+Wl5togOmKWLaGjJ7nHyMqedNVRiy68WbxITKLJSVvHpGqv+/xpj9bUko1gMluxmnLLbVN8SaETZpFotNKgdM9k/,iv:f2Rxg/k+FusaY6InOSRxi2js9wGdvyrdBMEj8+D5bbY=,tag:V3ygg5AvL/8R5SO8cK9dMw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1450t7kgj6ns5pflgng9fuyn96nffs6svfy7ssx37v4qthkjesezqrxrzn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZEhoZjM3a2hxNXVPbkdz
            bzNHUm91SGRZd3J1QTNqYTRIcVkvN2xERnlRCmhWWWd0QlV4bFdoYnVxN002NkN4
            ZmJvNWxxdkVucEg0Q2l3eFJaNHNJd3cKLS0tIE41SU5ZSjF2L0FsMks2cnYwM1h6
            ditvNEJ4K3lCVnU3VVJDRHNaSTYwNFUKe0v8EGhrOdz3x9XHh7lplfKLjPQz7n9c
            lrigE/n1p6CjQ8xj7Ww9mHiD2/OA9EHqMRQoojDVYDj0EYxgeZJobQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T11:40:42Z"
    mac: ENC[AES256_GCM,data:Om7UBTRyww1yD67m86xJWZVd5aXowTvvRiMVkjThTBCjqO95ZFd7HZvGvKuNGcyzAJFKPAPIGmmmKtMIH5BnT3PNw8aEw2b+6+DODY0QAaIxn1sTFqnobV4kixUbHdQjNfps7gNKJQzfHalXnqfxD7Ztaz3YjhvQvOrwXlqLfNM=,iv:7H1aVdoVFwMXOrmyLPN75R5uNaOjdhJrnAbo5aODwc0=,tag:ooD2SD5bRRAiArsniXx85A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
