apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PAAy/LnSZX+EHI+lfFZ1pontka8ZQoGvQar0iBl2JvcLddyswozsHLsvWrsMoRHKF5g2ZboB2ZaUXgPTaL5QaqAN6vhq0bCFVmjpMjAzSrUnW7mwu5OnzXIFEnD2e4ikj+DozRfivbM9uFFcUOFbZ9XuSkC/5esAYAcUCmjMezNJalEhpflVwCNf0TIuspW+mAPFCJV4KUVICSWZzEMpaIS1BV8dkTLg+M554A8YGyBd0Su6KIEmS3st/RMMduu707/NlFSxGwo07u68jLSQI+t/hvkliDGE6TFKAFuLnuOqLg1L/eltwtDkGnNvalfc+Y0aVVLY78O5hELpvYQjDfuPtGM75SFkZ1d40NQpPIjN8CmpiAdTRaC5wvBe0rq1,iv:WnLn4zdYZPaFds4OYOa8ZKi2W5qabab94PdyW1XZtZ4=,tag:gWszQz9IpKfDXb0vhgi0nw==,type:str]
    identity.pub: ENC[AES256_GCM,data:XFqRkqloWUaoTya6qPy7dm4pFCXgLLwdxwHBLy5g/d7vFEFlXk4kN3XQ+Ua0I+a7/0ay8She8KHoMytlrQAkOUnAtlL7tmGV9aeKkD8ENcfXvMYk9Qbr/VhMx43rpDjkjH2CyCwlcfva2l2py/4BXj39f1Aeh/8BWyUX/bXSxOGRafBsrCiIIpt9yd9nkt79a8H9c4yiLKAwnQ4pLoW24j6GdDcqUN9P+NI0L3zcHyYtfp7X2+l/nevdNQGUAraACGPQ7GzmSKsyoYZzSw==,iv:F1A9sOP7wEIeA9CdKRg3Moh/Z0qRB3yUHeSmSieR7j8=,tag:U8UIAXMzUDBBxNIIXmCsRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PPcZ9JtC5ebby6Cv6LSAU1KDLUFl6f7r1g0L8okyi8u9d4+ArdpS6MP5ACowa1DhstoCyYsSaZfNJEZ0nRpYvktew2hwGXvcvTTYBqGHtxRJOjyKpP5I7O1N8FIu0ZmRi4sUObLr+mWVyj4BO9ZeGpjohg/YOMXmJohTu6pP1OUGHRsFlVUd7gt84ZztSk6dsK8X0zjoSQOgGyjgUa7ZFBHe8vVCbWzcOCL9,iv:rMOLSUnytC9LvRAcpOjZv9DriTSKU/LIk+hIokgkw5o=,tag:ZoMURuSc23Sf6PbYcIWbRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1450t7kgj6ns5pflgng9fuyn96nffs6svfy7ssx37v4qthkjesezqrxrzn9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV25YTDRZMitmb3lnMkxy
            dGUzdC9NSXhMallXcEVzTmNYNVdZcWlZN1VNClZCbkF2bFRwcVRYY0pwSnNJMlpF
            N1MwdXQvRGhzKzVnVFJWTU93ekJqSjgKLS0tIDNDTXBoZ0JSUDE4bno5aWJqaDNo
            OE8wYVkray9pUjJRSUpkT3pNQkNzdTgKCMjuB/XnyP8QRi3IhCnlzjutprrpFVrp
            K+TpnXgTgGHta3osSH3fYPy5cpTi+UgNSX95XkYhe9LSoE3otAT9zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T16:05:45Z"
    mac: ENC[AES256_GCM,data:twayse+g39phB0mobXcCAjyyNT93X5KDcyAQvOM+Jx0zg7/7ZvMA0hvVkTF9bAB1f/r8q6Z4rxUlAMb7eQZ+xycSejFce+ohyvSJVeFOAiA6siQHd1q3tgRHLL3c/b6BIU0vrSlh3nAHp7lqxivPUu6SKeVt91DU3EP1Yq+WrUQ=,iv:R/KIbt3vYA3+Pnt6Dq46HHXvyT8xFkPdspNVLYSRWU0=,tag:aPKb+LVCOOnSytU2LWhuFg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
