apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:thhkJu9S7rmoXEhZxDTZC+2a1knqZr+OqEBsFAJzrD1g2M4Ki7Y2sGyaaY7b6jmizg4V/OV3E2kjoK98vlAg1e0K5qMnGSmFhBlcuI0WxxCNNjR4HC8rBVd0CrbFyDTAK1Kvp2a6dqxk+LF0hNugNbAwnwfrpcYgzvxu/QWdJiz7YhYOHZTbZVZKAdwJBmkuL0RCJELrbhVxPQ49cEbW+RfEzd1A63CR7pdeF/4mUEC0COp+x8RHO/boA2B2maQnK2VbsC9vPIfWytavZQpsH2k6KPBNUWvGzP57I8SHOyu4te2vI5iZEl3lS5COLICee5X3YKOxqFs++LIupH6+cBxQfGOXyumh+1PherID6CBas1dHGsXOJE1vnwx7SMLY,iv:0tZ47pEIy2nyb6De3zh+zrzf8cMnnPnNY1Gia+6cAXE=,tag:zya4Q8OhEmo5jN61YrZ+nA==,type:str]
    identity.pub: ENC[AES256_GCM,data:x0GGFOr5hSBZNmXik8CH396m40aVHgQycsNVzrEf196rsJH/7PtOEt28iwBLb9kxNYe7GcVzP0/Yfdzix0ehVkJVlpgIZTFydCWpIURrZ+eHfJeGJtqJqGqmfGQ6FhTGdwS9KHMrfvepWHclqXYcOGN5SQJ+ow3UUMDT2dtSBxEfqNRJ/7hwvtWmTh05Z8Ysbvqcs/hX3uLlvC0wsLZl90QLKcWMroQzp94MdCDvLcTeegUtERppObq+CV3stD1pX90NVTVSDmNXoVu+KA==,iv:2ePaawoLCYhRNi0JjB/hHvfAtCfVHt36F23OxItFY68=,tag:k8x271k56J7pgOmm3ZD1uA==,type:str]
    known_hosts: ENC[AES256_GCM,data:n2Ko9xHHKtsT4NFzhobpCv9LseXED4o8DZKEzN1hue8+MyLNu+wMXpgaH6vu6RieEUhsUs46aj1KHa7wjITXKCE27yWAz6dbinPXHlo8zRKzpPRIx81WUDvqCUq1DroZROp7INynZc9oDPrnOJoDwsQ8IY9dSjLp1TH7+Kh4SdrFLetD5qKnj4Z8pvXHSOY1g2lnQwCWwgelbVqjU9mbs7OUE0lcARS+Un0G,iv:hdSAUyH51HMGnNn7xRker6IZrS9uWpagSll4LmuXTEE=,tag:GtbOQblw1HSDu6fPOn/Z/g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14hngwnq493rx5u9vfera7cg66zxv8kax6w8lesh0q84m7uu0za6svawp49
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdGdQTjZjLzR1VHY3Ty9I
            ZUtWWXc0T0hpSUl2SlNFOUFIRWVjekxQaXpVCklUYnc0eGkySUYwcVpIdGFremhG
            TXFEVGpVbmVxa2ttdXV5MUh2bHhTU28KLS0tIHMvb1dMcXdFWkVEdUlGU3A5U1lS
            UmJucE54NERNSEhmQzlDQWlUclZHTXMKy3pe2Q6eWK1RdWgbl0JQwieB+Bhr1HJf
            JUYQb0NwR8fqXVeo93IT3e1gLageQ+75NRSltFiAZqP9A0+6ryH5IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T14:33:48Z"
    mac: ENC[AES256_GCM,data:eIAWC6AMANNU9qTHRw3qcTp6O5efOXh42pT7kxwLYUFtvSrsEfjcXj9CYq8JvACxA0crH/cngeAUL1fEwo2Fr/aHK7S/Btq6V9wZW6bD5ofCcF/qWporOxYqavzlZ2hnls9nyO0gvKhG39JVeF+c7vKoDx4KqJSp0w9/YQ4juv8=,iv:OT1zztwnmLfz051Bp9MCRPlcTVU80HLqllzsXRBwdSk=,tag:0ISMvbUVJetuc+VGL8xrMg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
