apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:phjOyE5xMUCtj8e9KKCllfWDK+v6Qv5njkDoxNsPZaF1eErpnmg7McSBrAorBB82KtFiLgZr7uZldNyOXofIEIT/7a4KcpWLlOJ/5/h44LX4IEHMN7rnWpN0Tuux1etx0ZW0UeyVJ+zcckDuu5q/j+ICql9Edzjb5yCQzlAzZr28YE1pbmzAlvpKx8B2cJgSIEe2P/3tFndDMwpEh1MKD3m+2pL7kfzuwkxTHLfl/5YCQW63v7AQ60BdUpNk2iNSxkz10LM+azfXuWM8mw9gTfxQWgxs069jhlXDW6fCQpoBED9DWRcYv9Zvd5y9NxDeG04PrDBM0pV6P8h+r1i52xMNB8Xb2DvjDzohRTfJTFCKxOl5ia1/39L1BCy9/iJQ,iv:tSHhTVfgebtNPpjyjmD7sOpWmBBTQNwSF0jxl843Vi8=,tag:FSICQI+NHF/Xj4FFPbbJPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:pemHxgIkw9+tAv9BzTOfEarHbtV4XrfPOl85vihkpfzMaRD5tfaBxFSgplPleyHTY2C8pbC9xPvXw44lKW5HfK9+KSnIQY1Hb68KHDXjT7PKR01djAl5uRiNXCd0pOpUlAYuS4CpKWrKxRKDHHfOYcRk8VxJpigiGdfndVwrDmzTKu4XwJ+7eR9EFWcUJ1lRl6xmmeX7N/O6LD/noaxy1yDFJA8jWl19rh8HJqpWrULu49H+6u6RnkpHT6o8ufZtB9E5XfSIR+wubi0/zQ==,iv:3hM6+zfuLnaNBUjWJf9SZ46uAc6mw/Mgsk46XYpSkUg=,tag:T5/IJUoM85qC/wb6DUhU4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pc0teKtxPQWU/J9ffFik4FTwMapEW6ffvdaBL2zoVoEvIlJ1HtBu16PeJ5xHTfWxEFK+3o25dXU7ntoWAdPRW8ZR/w17Ad3rX+sdSBV+3UoWJPmftVp31BzPFOLURIQ/dxgreAL9STpOeDI/QFk8zgtj/975hkp72IHqzsrw1uBeCaOA1JCu0I9BTMe1iA0WvNyexi3nVqEF9764TF2NSlL4xv5q0I4H9oHW,iv:ffPuFCOiTVQPKjdFYiQRtxo80zYNZVI4ZcsZumfrQmM=,tag:3/P4IgsoETHe4lTNoxfvsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1faczphw63ck4q6qx66qywephezpmefzdctw0scjve9mytk5jce8sqmc4v7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OWlyVnRhK2VRUDA4OEcy
            V2NMUnNBbzRCdndVbDZ4Y2dtWHN3SUQ0cldVClB4cDlnNmtSdVE4ejMwWjBVb01Y
            d050UlFKb2FDSU11d2xydlh1N2piVzQKLS0tIHl4T2txWThNZWp1K0JQbFQ2R0xP
            YzJHaGpjNy80MDlTSWtDRlgwbmtpTW8KxTxIRJntggzhnqRTSigbr7kwG49oqjWE
            9H/CcBuYi1O3+U9+9OF+2kFwBbNneOcMEbaOxBOGnufhKDrWT2YQ+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T12:37:11Z"
    mac: ENC[AES256_GCM,data:4utZrqJiIWGjx9C/JFG6zWJJG8OowU0m3GAtZiSZa80xrQWlS4uPS5+qSLpiE0jYv4TXGT0qtdwqrAmodw2CjQpqGqsDtn7nhq8tHAjwQjvpyGBa1yRe40+uUA8n+w12hdq8itHTcJfFz6KRY1DrXzPmK9xo58ziFvepu9ze4eU=,iv:jyRIFare25VcmhqXh9jmcom89fThnOuPJc9Yy3lMSyg=,tag:ffGXRTtrRYbAaUxsNbsZfw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
