apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.6.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  values:
    plex:
      serverIP: 192.168.0.16
      disableGDM: true
      requireHTTPS: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.16
        ports:
          main:
            port: 32400
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.0.2
        path: /mnt/HomeNas/SMBShare
        mountPath: /media