---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deployment:
      enabled: 2
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.io/ip-allocated-from-pool: main
        metallb.io/loadBalancerIPs: ${TRAEFIK_IP}
        metallb.universe.tf/ip-allocated-from-pool: main
      spec:
        externalTrafficPolicy: Local
    ingressClass:
      enabled: true
      isDefaultClass: true
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true    
    ports:
      traefik:
        expose:
          default: true
      web:
        redirections:
          port: websecure
      websecure:
        tls:
          enabled: true
          options: "default"

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: tk.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix