apiVersion: v1
kind: Service
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  selector:
    app.kubernetes.io/name: longhorn-frontend
    #app: longhorn-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.0.16
status:
    loadBalancer:
      ingress:
      - ip: ${TRAEFIK_IP}
