apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
      traefik.frontend.passHostHeader: "false"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
      traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  # ... other specifications ...
  selector:
    app: longhorn-frontend
  ports:
    main:
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.0.16
status:
    loadBalancer:
      ingress:
      - ip: ${TRAEFIK_IP}
