apiVersion: v1
kind: Service
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.0.16
status:
    loadBalancer:
      ingress:
      - ip: ${TRAEFIK_IP}
