apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 20.6.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    jellyfin:
      serverIP: 192.168.0.16
      disableGDM: true
      requireHTTPS: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
        ports:
          main:
            port: 8096
    persistence:
      media:
        enabled: true
        type: nfs
        server: ${TRUENAS_IP}
        path: ${MEDIA_SHARE}
        mountPath: /media
    ingress:
      main:
        enabled: true
        ingressClassName: # "external"
        hosts:
          - host: jf.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
          homepage:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod