apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jellyfin
            version: 20.6.13
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    timeout: 20m
    maxHistory: 3
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds:CreateReplace
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
      keepHistory: false
    values:
      portal:
        open:
          enabled: true
      global:
        stopAll: false
      jellyfin:
        serverIP: ${JELLYFIN_IP}
        disableGDM: true
        requireHTTPS: false
      service:
        main:
          type: LoadBalancer
          loadBalancerIP: ${JELLYFIN_IP}
          ports:
            main:
              port: 8096
              targetPort: 8096
      persistance:
        config:
          enabled: true
          mountPath: "/config"
        cache:
          enabled: true
          mountPath: "/cache"
          type: "emptyDir"
        transcode:
          enabled: true
          type: emptyDir
          mountPath: /config/transcode
        media:
          enabled: true
          type: nfs
          server: ${TRUENAS_IP}
          path: ${MEDIA_SHARE}
          mountPath: /Media
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  JELLYFIN_PublishedServerUrl: "{{ $.Values.chartContext.appUrl }}"
      autodiscovery:
        enabled: true
