apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
    interval: 15m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jellyfin
            version: 20.6.13
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    maxHistory: 3
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
      keepHistory: false
    timeout: 20m
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      #jellyfin:
        #serverIP: ${JELLYFIN_IP}
        #disableGDM: true
        #requireHTTPS: false
      service:
        main:
          type: LoadBalancer
          loadBalancerIP: ${JELLYFIN_IP}
          ports:
            main:
              port: 8096
              targetPort: 8096
      persistance:
        media:
          type: pvc
          static:
            mode: smb
            user: ${SMB_USER}
            password: ${SMB_PASS}
            share: ${SMB_SHARE}
            server: ${SMB_SERVER}
            mountPath: /Media
          #enabled: true
          #type: nfs
          #path: ${MEDIA_SHARE}
          #server: ${TRUENAS_IP}
          #existingClaim: media-nfs-pvc
          #mountPath: /Media
        config:
          enabled: true
          mountPath: "/config"
        cache:
          enabled: true
          mountPath: "/cache"
          type: "emptyDir"
        transcode:
          enabled: true
          mountPath: "/config/transcodes"
          type: "emptyDir"
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  JELLYFIN_PublishedServerUrl: "{{ $.Values.chartContext.appUrl }}"
      autodiscovery:
        enabled: true
