apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 20.6.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
        ports:
          main:
            port: 8096
    persistence:
      media:
        enabled: true
        type: nfs
        server: ${TRUENAS_IP}
        path: ${MEDIA_SHARE}
        mountPath: /media
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          hosts: jf.${DOMAIN_0}
          clusterIssuer: domain-0-wildcard
        hosts:
          - host: jf.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix