apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 20.6.13
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    jellyfin:
      serverIP: 192.168.0.16
      disableGDM: true
      requireHTTPS: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}
        ports:
          main:
            port: 8096
    persistence:
      smb-vol:
        enabled: true
        type: pvc
        static:
          mode: smb
          user: ${SMB_USER}
          password: ${SMB_PASS}
          share: ${SMB_SHARE}
          server: ${SMB_SERVER}
#    persistance:
#      media:
#        enabled: true
#        type: nfs
#        path: /mnt/HomeNas/SMBShare #${MEDIA_SHARE}
#        server: 192.168.0.2 #${TRUENAS_IP}
#        mountPath: /media